### ISSUE TITLE
kind, name and steps are not recognized as yaml properties

### ISSUE THREAD

**Issue by HitLuca** [redhat-developer/vscode-yaml#243]
When opening my Drone CI yaml file, errors are given about the keys `kind`, `name` and `steps` not being valid properties. The opened file is a valid [drone yaml file](https://docs.drone.io/configure/pipeline/overview/), so I guess there is no support by this extension. 

![error_messages](https://user-images.githubusercontent.com/7645621/67899267-50920d00-fb38-11e9-9f3a-7e0253bf8d76.png)

Would support for those keys be added in the future? In case the problem is another, any useful pointer would be greatly appreciated

**Comment by HitLuca** [comment]
Closed as support for custom yaml tags is given by editing settings.json

**Comment by zerosym** [comment]
By default all the schemas are pulled from http://schemastore.org/json/ but I think their schema for drone is outdated?

Related issue in their repository:
https://github.com/SchemaStore/schemastore/issues/814

**Comment by HitLuca** [comment]
Thank you very much, I am not an expert of how yaml works, sorry to have opened an issue in the wrong place!

**Comment by zerosym** [comment]
@HitLuca  Upon closer inspection it might be an issue for here after all.  The schema file in schemastore repo seems up to date (was last pushed only a couple weeks ago) and I've had luck with validating my own drone.yml file by modifying the schema slightly.  Specifically, the lack of a top level "properties" key seems to be causing the validator issues, even though an array of them is defined under "oneOf".

It could be because the drone schema references the latest version of JSON spec which may not be fully implemented yet in vscode-yaml (https://github.com/redhat-developer/vscode-yaml/issues/222).

It's either that or the schemastore spec for drone is incorrectly written -- I don't have the knowledge to tell either way.

**Comment by ig0rsky** [comment]
@zerosym The JSON spec for drone.yml is outdated. :)

**Comment by kevinkjt2000** [comment]
I concur with zerosym; it seems that the drone spec is already updated and that #222 is the culprit.

@ig0rsky `kind`, `name`, `steps`, and other properties were merged in https://github.com/SchemaStore/schemastore/pull/823 before this issue was opened. What remains as outdated? Perhaps I'm missing crucial detail here being new to all of these projects.

**Comment by JPinkney** [comment]
I think #222 should be fixed, I just haven't closed it yet (though I'm going to double check). I can't see any obvious reasons why the schema validation isn't working correctly.

The JSON language server also fails on this schema:
```JSON
{
    "$schema": "http://json.schemastore.org/drone",
    "kind": "pipeline",
    "type": "docker",
    "name": "default",
    "steps": [
      {
        "name": "backend",
        "image": "golang",
        "commands": [
          "go build",
          "go test"
        ]
      },
      {
        "name": "frontend",
        "image": "node",
        "commands": [
          "npm install",
          "npm run test"
        ]
      }
    ]
}
```

**Comment by iatsiuk** [comment]
I've tried to add this settings with no success so far:

```json
"yaml.schemas": {
    "https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/drone.json": [
        ".drone.yml"
    ]
}
```

<img width="533" alt="Screenshot 2020-03-13 at 9 36 35 AM" src="https://user-images.githubusercontent.com/24681814/76599677-27ce4b00-650e-11ea-9dc3-c68b80f11ac1.png">

@HitLuca could you please reopen this bug as it's not solved.

**Comment by JPinkney** [comment]
AH! I finally figured it out. It ended up being a schema issue but this was one of the oddest bugs I've had to track down.

So it turns out that the drone schema sets additionalProperties to false for the root object: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/drone.json#L4

According to the json schema spec:
> The additionalProperties keyword is used to control the handling of extra stuff, that is, properties whose names are not listed in the properties keyword.

In the schema there is no root properties keyword, meaning that everything is considered an additional property and that's why the errors appear.

I'm going to send a PR to the json schema store and close this issue.

**Comment by jeffwidman** [comment]
Thanks @JPinkney! Looks like this is your PR: https://github.com/SchemaStore/schemastore/pull/993

It's already been merged, so will that update show up automatically in VSCode for me or does something need to be bumped in this repo to start pulling in the new version?

**Comment by JPinkney** [comment]
@jeffwidman It should automatically update if you restart VSCode

**Comment by jeffwidman** [comment]
Perfect thx

**Comment by unfor19** [comment]
@JPinkney - thanks for the details, I had a similar issue when I tried to use `environment` in `pipeline_docker` so I created an issue and a PR - https://github.com/SchemaStore/schemastore/issues/1129

I was wondering if anyone else is experiencing the same issue

**Comment by julioflima** [comment]
I'm.

**Comment by unfor19** [comment]
@julioflima this was already resolved. If you experience the same thing, please provide more details

**Comment by julioflima** [comment]
Follow my version of VS Code:
`Version: 1.53.2`
`Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4`
`Date: 2021-02-11T11:48:44.518Z`
`Electron: 11.2.1`
`Chrome: 87.0.4280.141`
`Node.js: 12.18.3`
`V8: 8.7.220.31-electron.0`
`OS: Linux x64 5.4.70-amd64-desktop`


Follow in below my example of yml.
https://github.com/julioflima/Platiot/blob/master/.github/workflows/backend-deploy.yml

I've tried schemas, with no good.

![image](https://user-images.githubusercontent.com/17098382/107855543-b96ec880-6e01-11eb-851b-8c7a33893e77.png)

**Comment by unfor19** [comment]
@julioflima It's not related to the issue, you're talking about a different schema.json (deployphp/deployer), this issue talks about Drone CI's schema.

Make sure your filename is `.drone.yml`

**Comment by julioflima** [comment]
I realized it right now.

**Comment by julioflima** [comment]
But maybe you should give me a solution. Maybe the problem is the name.
